#!/usr/bin/env python3
r"""Emit ``paper/numbers.tex`` from the results tree.

Every quantity quoted in the manuscript is a macro defined here, so the text can
never drift from the run that produced it.  If a stage has not been run the
macro is defined as ``\todonum{...}``, which typesets visibly rather than
silently printing a stale number.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import pandas as pd


def _fmt(x, nd=3):
    try:
        v = float(x)
    except (TypeError, ValueError):
        return None
    if v != v:
        return None
    return f"{v:.{nd}f}"


def _epkey(name: str) -> str:
    """CamelCase, digit-free key for an endpoint name.

    LaTeX control sequences are letters only: ``\redMortality30dAvoided`` parses
    as ``\redMortality`` followed by the text ``30dAvoided``, which fails in a
    way whose error message points nowhere near the cause.
    """
    # drop whole tokens that begin with a digit ("30d", "7d", "48h"): stripping
    # only the digits would leave "Mortalityd"
    words = [w for w in name.split("_") if w and not w[0].isdigit()]
    return re.sub(r"[^A-Za-z]", "", "".join(w.capitalize() for w in words))


def _pct(x, nd=1):
    v = _fmt(x, nd + 2)
    return None if v is None else f"{100 * float(v):.{nd}f}"


#: Every macro the manuscript may reference.  Listing them explicitly is what
#: lets the paper compile before every stage has run: a quantity that is not yet
#: available becomes a visible ``[?name]`` marker instead of an undefined control
#: sequence, so a half-finished run produces a readable draft rather than a
#: LaTeX error, and a stale number can never survive unnoticed.
REQUIRED = [
    "thyAllHold", "thyTrialsJS", "thyIdentityRelErr", "thyIdentityTrials", "thyPviErr",
    "simRecovery", "simRecoveryCorrected", "simRegimeAccuracy", "simMaxN",
    "simThmOneHolds", "simThmTwoHolds", "simThmThreeRelErr",
    "simRecoveryFloor", "simSubsetsScored", "simSubsetsBelowFloor",
    "simRecoveryFullPanel", "simMeanAbsErr", "simRegimeMaxN",
    "simSynergyFirstN", "simRedundancyFirstN",
    "powBothFrac", "powEventsMin", "powEventsMax", "powSynMin", "powSynMax",
    "powTreeSynMax", "restrictedShareMin", "restrictedShareMax",
    "redAvoidedMin", "redAvoidedMax",
    "redIcuTransferAvoided", "redIcuTransferSaved", "redIcuTransferCert", "aurocIcuTransfer",
    "redAkiAvoided", "redAkiSaved", "redAkiCert", "aurocAki",
    "redHfReadmissionAvoided", "redHfReadmissionSaved", "redHfReadmissionCert", "aurocHfReadmission",
    "redMortalityAvoided", "redMortalitySaved", "redMortalityCert", "aurocMortality",
    "cohortN", "cohortSubjects", "cohortSource", "primaryPrevalence",
    "primaryBaselineBits", "primaryFullBits", "primaryBaselineAuroc",
    "primaryFullAuroc", "primaryNullGap", "primaryIdentityRelErr",
    "primaryRestrictedBits", "primaryRestrictedShare", "primarySeedShare",
    "primaryMonoViolations", "primaryMonoWorst",
    "redTestsAvoided", "redCostSaved", "redCostSavedPct", "redAuroc",
    "redAurocAll", "redCertifiedLoss", "redInfoGap",
    "gainMaxGini", "gainMinGini",
    "interNRedundant", "interNSynergistic", "interNPairs",
    "interMostRedundantPair", "interMostRedundantBits",
    "interRegimeFlips", "interNEndpoints",
]
#: Per-modality macro families, expanded over the modalities the paper discusses.
MODALITIES = ["Labs", "Ecg", "Cxr", "Echo", "Notes"]
for _m in MODALITIES:
    REQUIRED += [f"dec{_m}Marginal", f"dec{_m}Conditional", f"dec{_m}Redundant",
                 f"dec{_m}Synergistic", f"dec{_m}RedFrac",
                 f"gain{_m}Mean", f"gain{_m}PNinetynine", f"gain{_m}Gini",
                 f"gain{_m}Concentration", f"gain{_m}FracAbove"]
for _e in ("Mortality", "HfReadmission", "Aki", "IcuTransfer"):
    for _m in MODALITIES:
        REQUIRED += [f"dec{_m}{_e}Marg", f"dec{_m}{_e}Cond",
                     f"dec{_m}{_e}Red", f"dec{_m}{_e}Syn"]


class Macros:
    def __init__(self) -> None:
        self.values: dict[str, str] = {}
        self.notes: dict[str, str] = {}
        self.missing: list[str] = []

    def add(self, name: str, value, note: str = "") -> None:
        if value is None or value == "":
            return
        self.values[name] = str(value)
        if note:
            self.notes[name] = note

    def text(self) -> str:
        names = list(dict.fromkeys(REQUIRED + sorted(self.values)))
        lines = []
        for n in names:
            if n in self.values:
                suffix = f"  % {self.notes[n]}" if n in self.notes else ""
                lines.append(f"\\newcommand{{\\{n}}}{{{self.values[n]}}}{suffix}")
            else:
                self.missing.append(n)
                lines.append(f"\\newcommand{{\\{n}}}{{\\todonum{{{n}}}}}")
        head = ("% Auto-generated by scripts/make_paper_numbers.py -- do not edit.\n"
                "% Quantities from stages that have not run typeset as a visible marker\n"
                "% rather than as a stale value or an undefined control sequence.\n"
                "\\providecommand{\\todonum}[1]{\\textbf{[?#1]}}\n\n")
        return head + "\n".join(lines) + "\n"

    @property
    def lines(self) -> list[str]:
        return self.text().splitlines()


def load_json(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def load_csv(p: Path):
    return pd.read_csv(p) if p.exists() else None


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default="results")
    ap.add_argument("--cohort-name", default="cohort_synthetic")
    ap.add_argument("--primary", default="mortality_30d")
    ap.add_argument("--out", default="paper/numbers.tex")
    args = ap.parse_args()

    R = Path(args.results)
    M = Macros()

    # ---- theory verification ------------------------------------------- #
    thy = load_json(R / "theory" / "verification.json")
    if thy:
        reps = {r["name"]: r for r in thy["reports"]}
        M.add("thyAllHold", "yes" if thy["all_hold"] else "NO")
        M.add("thyTrialsJS", reps.get("I <= H(pi) * TV", {}).get("n_trials"))
        ident = reps.get("Thm3 identity: dI = int dNB dt/t", {})
        M.add("thyIdentityRelErr", f"{abs(ident.get('worst_slack', float('nan'))):.1e}"
              if ident else None)
        M.add("thyIdentityTrials", ident.get("n_trials"))
        pvi = next((k for k in reps if k.startswith("PVI recovers")), None)
        M.add("thyPviErr", f"{abs(reps[pvi]['worst_slack']):.1e}" if pvi else None)

    # ---- simulation validation ----------------------------------------- #
    sim = load_json(R / "simulation" / "summary.json")
    if sim:
        M.add("simRecovery", _pct(sim.get("recovery_at_largest_n")))
        M.add("simRecoveryCorrected", _pct(sim.get("recovery_after_correction")))
        M.add("simRegimeAccuracy", _pct(sim.get("regime_accuracy"), 0))
        M.add("simMaxN", f"{max(sim.get('sizes', [0])):,}".replace(",", "{,}"))
        M.add("simThmOneHolds", "yes" if sim.get("theorem1_all_hold") else "NO")
        M.add("simThmTwoHolds", "yes" if sim.get("theorem2_all_hold") else "NO")
        t3 = sim.get("theorem3", {})
        M.add("simThmThreeRelErr", f"{t3.get('rel_error', float('nan')):.1e}"
              if t3 else None)
        M.add("simRecoveryFloor", _fmt(sim.get("recovery_floor_bits"), 2))
        M.add("simSubsetsScored", sim.get("n_subsets_scored"))
        M.add("simSubsetsBelowFloor", sim.get("n_subsets_below_floor"))
        M.add("simRecoveryFullPanel", _pct(sim.get("recovery_full_panel")))
        M.add("simMeanAbsErr", _fmt(sim.get("mean_abs_error_bits"), 4))
        M.add("simRegimeMaxN", f"{sim.get('regime_max_n', 0):,}".replace(",", "{,}")
              if sim.get("regime_max_n") else None)
        fc = sim.get("regime_first_correct") or []
        syn = [r for r in fc if r.get("true_regime") == "synergistic"
               and r.get("first_correct_n", -1) > 0]
        red = [r for r in fc if r.get("true_regime") == "redundant"
               and r.get("first_correct_n", -1) > 0]
        M.add("simSynergyFirstN",
              f"{min(r['first_correct_n'] for r in syn):,}".replace(",", "{,}")
              if syn else None)
        M.add("powBothFrac", _pct(sim.get("power_both_present_frac"), 0))
        M.add("powEventsMin", sim.get("power_events_min"))
        M.add("powEventsMax", sim.get("power_events_max"))
        M.add("powSynMin", _pct(sim.get("power_syn_recovered_min"), 0))
        M.add("powSynMax", _pct(sim.get("power_syn_recovered_max"), 0))
        M.add("powTreeSynMax", _pct(sim.get("tree_syn_recovered_max"), 0))
        M.add("simRedundancyFirstN",
              f"{min(r['first_correct_n'] for r in red):,}".replace(",", "{,}")
              if red else None)

    # ---- primary endpoint ------------------------------------------------ #
    base = R / args.cohort_name / args.primary
    s = load_json(base / "summary.json")
    if s:
        c = s["cohort"]
        M.add("cohortN", f"{c['n']:,}".replace(",", "{,}"))
        M.add("cohortSubjects", f"{c['n_subjects']:,}".replace(",", "{,}"))
        M.add("cohortSource", c.get("source", "").replace("_", "-"))
        M.add("primaryPrevalence", _pct(c["prevalence"], 1))
        info = s["information"]
        M.add("primaryBaselineBits", _fmt(info["baseline_bits"], 4))
        M.add("primaryFullBits", _fmt(info["full_panel_bits"], 4))
        M.add("primaryBaselineAuroc", _fmt(info["baseline_auroc"]))
        M.add("primaryFullAuroc", _fmt(info["full_panel_auroc"]))
        M.add("primaryNullGap", _fmt(s.get("null_gap_bits"), 5))
        ic = s.get("identity_check", {})
        M.add("primaryIdentityRelErr", f"{ic.get('rel_error', float('nan')):.1e}"
              if ic else None)
        M.add("primaryRestrictedBits", _fmt(ic.get("restricted_bits"), 4))
        M.add("primaryRestrictedShare",
              _pct(ic.get("restricted_bits", 0) / max(ic.get("kl_bits", 1e-9), 1e-9), 0)
              if ic.get("kl_bits") else None)
        vdec = s.get("variance_decomposition_full_panel", {})
        M.add("primarySeedShare", _pct(vdec.get("seed_share"), 0))
        mono = s.get("monotonicity", {})
        M.add("primaryMonoViolations", mono.get("n_violations"))
        M.add("primaryMonoWorst", _fmt(mono.get("worst_violation_bits"), 4))
        red = s.get("reduction", {})
        if red:
            M.add("redTestsAvoided", _pct(red.get("tests_avoided"), 1))
            M.add("redCostSaved", _fmt(red.get("cost_saved"), 2))
            M.add("redCostSavedPct", _pct(red.get("cost_saved_pct"), 1))
            M.add("redAuroc", _fmt(red.get("auroc"), 4))
            M.add("redAurocAll", _fmt(red.get("auroc_all"), 4))
            M.add("redCertifiedLoss", _fmt(red.get("max_certified_nb_loss"), 5))
            M.add("redInfoGap", _fmt(red.get("info_gap_bits"), 4))
        gains = {g["modality"]: g for g in s.get("patient_gains", [])}
        for m, g in gains.items():
            key = m.capitalize()
            M.add(f"gain{key}Mean", _fmt(g["mean_bits"], 4))
            M.add(f"gain{key}PNinetynine", _fmt(g["p99_bits"], 4))
            M.add(f"gain{key}Gini", _fmt(g["gini"], 2))
            # the ratio, computed here rather than typeset as "a/b" in the text
            M.add(f"gain{key}FracAbove", _pct(g.get("frac_above_0.01"), 1))
            M.add(f"gain{key}Concentration",
                  _fmt(g["p99_bits"] / max(g["mean_bits"], 1e-12), 0))
        if gains:
            M.add("gainMaxGini", _fmt(max(g["gini"] for g in gains.values()), 2))
            M.add("gainMinGini", _fmt(min(g["gini"] for g in gains.values()), 2))

    dec = load_csv(base / "tables" / "decomposition.csv")
    if dec is not None:
        loo = dec[dec["context_kind"] == "leave_one_out"]
        for _, r in loo.iterrows():
            k = str(r["modality"]).capitalize()
            M.add(f"dec{k}Marginal", _fmt(r["marginal_bits"], 4))
            M.add(f"dec{k}Conditional", _fmt(r["conditional_bits"], 4))
            M.add(f"dec{k}Redundant", _fmt(r["redundant_bits"], 4))
            M.add(f"dec{k}Synergistic", _fmt(r["synergistic_bits"], 4))
            M.add(f"dec{k}RedFrac", _pct(r["redundancy_fraction"], 0))

    inter = load_csv(base / "tables" / "interaction_map.csv")
    if inter is not None and len(inter):
        M.add("interNRedundant", int((inter["regime"] == "redundant").sum()))
        M.add("interNSynergistic", int((inter["regime"] == "synergistic").sum()))
        M.add("interNPairs", len(inter))
        worst = inter.loc[inter["interaction_bits"].idxmin()]
        M.add("interMostRedundantPair", f"{worst['a']}--{worst['b']}")
        M.add("interMostRedundantBits", _fmt(abs(worst["interaction_bits"]), 4))

    # ---- cross-endpoint contrast ---------------------------------------- #
    per_ep = {}
    for oc_dir in sorted((R / args.cohort_name).glob("*")):
        sj = load_json(oc_dir / "summary.json")
        dec = load_csv(oc_dir / "tables" / "decomposition.csv")
        if sj is None or dec is None:
            continue
        per_ep[oc_dir.name] = (sj, dec[dec["context_kind"] == "leave_one_out"]
                               .set_index("modality"))
    if per_ep:
        shares = []
        for name, (sj, dec) in per_ep.items():
            ic = sj.get("identity_check", {})
            if ic.get("kl_bits"):
                shares.append(ic["restricted_bits"] / ic["kl_bits"])
            red = sj.get("reduction", {})
            key = _epkey(name)
            M.add(f"red{key}Avoided", _pct(red.get("tests_avoided"), 0))
            M.add(f"red{key}Saved", _fmt(red.get("cost_saved"), 0))
            M.add(f"red{key}Cert", _fmt(red.get("max_certified_nb_loss"), 4))
            M.add(f"auroc{key}", _fmt(sj["information"]["full_panel_auroc"], 3))
            for mod in ("labs", "ecg", "cxr", "echo"):
                if mod in dec.index:
                    r = dec.loc[mod]
                    mk = mod.capitalize()
                    M.add(f"dec{mk}{key}Marg", _fmt(r["marginal_bits"], 4))
                    M.add(f"dec{mk}{key}Cond", _fmt(r["conditional_bits"], 4))
                    M.add(f"dec{mk}{key}Red", _fmt(r["redundant_bits"], 4))
                    M.add(f"dec{mk}{key}Syn", _fmt(r["synergistic_bits"], 4))
        if shares:
            M.add("restrictedShareMin", f"{100 * min(shares):.0f}")
            M.add("restrictedShareMax", f"{100 * max(shares):.0f}")
        avoided = [sj.get("reduction", {}).get("tests_avoided")
                   for sj, _ in per_ep.values()]
        avoided = [a for a in avoided if a is not None]
        if avoided:
            M.add("redAvoidedMin", f"{100 * min(avoided):.0f}")
            M.add("redAvoidedMax", f"{100 * max(avoided):.0f}")


    rows = []
    for oc_dir in sorted((R / args.cohort_name).glob("*")):
        im = oc_dir / "tables" / "interaction_map.csv"
        if im.exists():
            df = pd.read_csv(im)
            df["outcome"] = oc_dir.name
            rows.append(df)
    if rows:
        allint = pd.concat(rows)
        flips = 0
        for (a, b), g in allint.groupby(["a", "b"]):
            regimes = set(g["regime"]) - {"indeterminate"}
            flips += int(len(regimes) > 1)
        M.add("interRegimeFlips", flips)
        M.add("interNEndpoints", int(allint["outcome"].nunique()))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    body = M.text()
    out.write_text(body)
    n_defined = len(M.values)
    print(f"wrote {out} ({n_defined} resolved, {len(M.missing)} pending)")
    if M.missing:
        print("  pending:", ", ".join(M.missing[:14]),
              "..." if len(M.missing) > 14 else "")


if __name__ == "__main__":
    main()
